import assert from 'node:assert/strict';
import test from 'node:test';

// Test condition logic as implemented in TriageCard
function isTriageInProgress(result) {
  if (!result) return false;
  return result.alertLevel === "IN_PROGRESS";
}

test('isTriageInProgress returns true only when alertLevel is IN_PROGRESS', () => {
  assert.equal(isTriageInProgress({ alertLevel: "IN_PROGRESS" }), true);
  assert.equal(isTriageInProgress({ alertLevel: "IN_PROGRESS", isFinalVerdict: false }), true);
});

test('isTriageInProgress returns false when alertLevel is RED, YELLOW, or GREEN regardless of isFinalVerdict', () => {
  // Even if isFinalVerdict is omitted or false
  assert.equal(isTriageInProgress({ alertLevel: "RED" }), false);
  assert.equal(isTriageInProgress({ alertLevel: "RED", isFinalVerdict: undefined }), false);
  assert.equal(isTriageInProgress({ alertLevel: "RED", isFinalVerdict: false }), false);
  assert.equal(isTriageInProgress({ alertLevel: "YELLOW" }), false);
  assert.equal(isTriageInProgress({ alertLevel: "GREEN" }), false);
});

test('Medical disclaimer text matches required exact statement', () => {
  const expectedDisclaimer = "Medical Disclaimer: This analysis is generated by AI and may make mistakes. It is not a substitute for professional clinical judgment. Please consult a qualified real doctor or healthcare provider. In an emergency, call 112 immediately.";
  assert.match(expectedDisclaimer, /Medical Disclaimer: This analysis is generated by AI and may make mistakes\./);
  assert.match(expectedDisclaimer, /In an emergency, call 112 immediately\./);
});
