import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Copy, HeartPulse, MapPin, Phone, Pill, ShieldAlert, Siren, UserRound } from 'lucide-react';
import { api } from '../../services/api';

export function EmergencyPublicPage({ token, onHelp, onNavigate }) {
  const [profile, setProfile] = useState(null), [loading, setLoading] = useState(true), [unavailable, setUnavailable] = useState(false), [locationError, setLocationError] = useState('');
  useEffect(() => { api.emergency.public(token).then(setProfile).catch(() => setUnavailable(true)).finally(() => setLoading(false)); }, [token]);
  const summary = useMemo(() => profile ? ['Emergency Profile', profile.displayName && `Name: ${profile.displayName}`, profile.bloodGroup && `Blood Group: ${profile.bloodGroup}`, profile.allergies?.length && `Allergies: ${profile.allergies.join(', ')}`, profile.criticalConditions?.length && `Critical Conditions: ${profile.criticalConditions.join(', ')}`, profile.importantMedicines?.length && `Important Medicines: ${profile.importantMedicines.join(', ')}`, profile.emergencyContact && `Emergency Contact: ${[profile.emergencyContact.name, profile.emergencyContact.relationship].filter(Boolean).join(' — ')} — ${profile.emergencyContact.phone}`].filter(Boolean).join('\n') : '', [profile]);
  const getHelp = () => { setLocationError(''); if (!navigator.geolocation) { setLocationError('Location access was not provided, so nearby facilities cannot be automatically detected.'); return; } navigator.geolocation.getCurrentPosition(position => onHelp({ latitude: position.coords.latitude, longitude: position.coords.longitude }), () => setLocationError('Location access was not provided, so nearby facilities cannot be automatically detected.'), { enableHighAccuracy: true, timeout: 7000, maximumAge: 0 }); };
  if (loading) return <main className="public-emergency"><HeartPulse /><h1>Loading Emergency Profile…</h1></main>;
  if (unavailable) return <main className="public-emergency"><ShieldAlert size={42} /><h1>Emergency Profile Unavailable</h1><p>This Emergency QR is invalid or no longer active.</p><button className="button secondary" onClick={() => onNavigate('First Aid')}>Open First Aid</button></main>;
  const section = (Icon, title, values) => values?.length ? <section><Icon /><div><span>{title}</span>{values.map(value => <b key={value}>{value}</b>)}</div></section> : null;
  return <main className="public-emergency"><header><HeartPulse /><b>SANJEEVANI</b><span>EMERGENCY PROFILE</span><h1>{profile.displayName || 'Patient Emergency Information'}</h1><p>Scan → Understand → Act</p></header><div className="public-emergency-facts">{section(HeartPulse,'BLOOD GROUP',profile.bloodGroup && [profile.bloodGroup])}{section(AlertTriangle,'KNOWN ALLERGIES',profile.allergies)}{section(ShieldAlert,'CRITICAL CONDITIONS',profile.criticalConditions)}{section(Pill,'IMPORTANT MEDICINES',profile.importantMedicines)}{profile.emergencyContact && <section><UserRound /><div><span>EMERGENCY CONTACT</span><b>{[profile.emergencyContact.name, profile.emergencyContact.relationship].filter(Boolean).join(' — ') || 'Emergency contact'}</b><a className="button secondary" href={`tel:${profile.emergencyContact.phone}`}><Phone size={18} />Call Emergency Contact</a></div></section>}</div><button className="get-help-button" onClick={getHelp}><Siren />GET HELP</button><p className="location-prompt">Allow location to find nearby emergency facilities. This uses the current device location only.</p>{locationError && <div className="location-denied" role="alert">{locationError}</div>}<div className="public-emergency-actions"><button className="button secondary" onClick={() => navigator.clipboard?.writeText(summary)}><Copy size={16} />Copy Emergency Summary</button><button className="button secondary" onClick={() => onNavigate('SOS Response')}><Siren size={16} />SOS</button><button className="button secondary" onClick={() => onNavigate('First Aid')}><MapPin size={16} />First Aid</button></div><footer>This information was voluntarily shared by the patient for emergency use.</footer></main>;
}
