import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, Bell, BellOff, Check, CheckCircle2, ExternalLink, Pill, Plus, Search, ShieldAlert, Trash2 } from "lucide-react";
import { api } from "../../services/api";
import { localToday } from "../../services/cycleCalculations";

const today = localToday;
const idOf = item => item?._id || item?.id;
const dateLabel = value => value ? new Date(value).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" }) : "Not recorded";
const medicineName = value => String(value || "").replace(/\b\w/g, letter => letter.toUpperCase());

function LabelSection({ title, text, tone = "standard" }) {
  if (!text) return null;
  return <details className={`medicine-label-section ${tone}`}><summary>{tone === "warning" && <AlertTriangle size={16} />}{title}<span>Show details</span></summary><div>{text}</div></details>;
}

function AddMedicineForm({ medicine, plans, onSave, saving }) {
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ formStrength: "", purpose: "", startDate: today(), endDate: "", status: "Current", prescribedBy: "", details: "", associatedPlanId: "" });
  const submit = async event => {
    event.preventDefault();
    const saved = await onSave({ ...form, category: "Medicine", title: medicine.name, medicineSourceId: medicine.id, medicineSource: medicine.source.name, dose: form.formStrength, doctor: form.prescribedBy });
    if (saved) setOpen(false);
  };
  if (!open) return <button className="button primary" onClick={() => setOpen(true)}><Pill size={16} /> Add to My Medicines</button>;
  return <form className="medicine-add-form" onSubmit={submit}><div className="medicine-section-head"><div><span className="section-kicker">PATIENT MEDICAL MEMORY</span><h3>Add {medicine.name}</h3></div><button type="button" className="text-button" onClick={() => setOpen(false)}>Cancel</button></div><div className="medicine-form-grid"><label>Form / strength<input maxLength="160" placeholder="From your prescription or label" value={form.formStrength} onChange={event => setForm({ ...form, formStrength: event.target.value })} /></label><label>Status<select value={form.status} onChange={event => setForm({ ...form, status: event.target.value })}><option>Current</option><option>Previous</option></select></label><label>Start date<input type="date" required value={form.startDate} onChange={event => setForm({ ...form, startDate: event.target.value })} /></label><label>End date (optional)<input type="date" value={form.endDate} onChange={event => setForm({ ...form, endDate: event.target.value })} /></label><label>Reason / purpose<input maxLength="500" value={form.purpose} onChange={event => setForm({ ...form, purpose: event.target.value })} /></label><label>Prescribed by<input maxLength="160" value={form.prescribedBy} onChange={event => setForm({ ...form, prescribedBy: event.target.value })} /></label><label>Associated tracker<select value={form.associatedPlanId} onChange={event => setForm({ ...form, associatedPlanId: event.target.value })}><option value="">None</option>{plans.map(plan => <option value={idOf(plan)} key={idOf(plan)}>{plan.title}</option>)}</select></label><label className="wide">Notes<textarea maxLength="2000" value={form.details} onChange={event => setForm({ ...form, details: event.target.value })} /></label></div><p className="medicine-form-note">Only enter strength or directions from your prescription or medicine packaging. Sanjeevani does not calculate dosage.</p><button className="button primary" disabled={saving}>{saving ? "Saving medicine…" : "Save to Medical History"}</button></form>;
}

const timeLabel = value => { const [hour, minute] = value.split(":").map(Number); return new Date(2000, 0, 1, hour, minute).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }); };

function ReminderEditor({ medicine, save, remove, busy, onPermission }) {
  const existing = medicine.reminder;
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState(() => existing ? { frequency: existing.frequency, times: existing.times, startDate: existing.startDate, endDate: existing.endDate || "", enabled: existing.enabled } : { frequency: "Once Daily", times: ["08:00"], startDate: today(), endDate: "", enabled: true });
  const setFrequency = frequency => { const count = { "Once Daily": 1, "Twice Daily": 2, "Three Times Daily": 3 }[frequency]; const defaults = { 1: ["08:00"], 2: ["08:00", "20:00"], 3: ["08:00", "14:00", "20:00"] }; setForm({ ...form, frequency, times: count ? defaults[count] : form.times.length ? form.times : ["08:00"] }); };
  const submit = async event => { event.preventDefault(); if (form.enabled) await onPermission(); if (await save(idOf(medicine), form)) setOpen(false); };
  if (!open) return <div className="medicine-reminder-summary"><div><Bell size={15} /><span><b>Reminder</b><small>{existing ? `${existing.enabled ? existing.times.map(timeLabel).join(" · ") : "Disabled"}` : "Not set"}</small></span></div><button className="button secondary compact" onClick={() => setOpen(true)}>{existing ? "Edit Reminder" : "Set Reminder"}</button>{existing && <button className="icon-button danger" aria-label={`Delete ${medicine.title} reminder`} onClick={() => window.confirm("Delete this medicine reminder?") && remove(idOf(medicine))}><Trash2 size={14} /></button>}</div>;
  return <form className="reminder-form" onSubmit={submit}><div className="medicine-section-head"><div><span className="section-kicker">MEDICINE REMINDER</span><h3>{medicine.title}</h3></div><button type="button" className="text-button" onClick={() => setOpen(false)}>Cancel</button></div><label>Frequency<select value={form.frequency} onChange={event => setFrequency(event.target.value)}><option>Once Daily</option><option>Twice Daily</option><option>Three Times Daily</option><option>Custom Time</option></select></label><div className="reminder-times">{form.times.map((time, index) => <label key={index}>Time {index + 1}<span><input type="time" required value={time} onChange={event => setForm({ ...form, times: form.times.map((item, itemIndex) => itemIndex === index ? event.target.value : item) })} />{form.frequency === "Custom Time" && form.times.length > 1 && <button type="button" className="icon-button danger" aria-label={`Remove time ${index + 1}`} onClick={() => setForm({ ...form, times: form.times.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 size={14} /></button>}</span></label>)}</div>{form.frequency === "Custom Time" && form.times.length < 8 && <button type="button" className="button secondary compact" onClick={() => setForm({ ...form, times: [...form.times, "12:00"] })}><Plus size={14} /> Add time</button>}<div className="reminder-date-grid"><label>Start date<input type="date" required value={form.startDate} onChange={event => setForm({ ...form, startDate: event.target.value })} /></label><label>End date (optional)<input type="date" min={form.startDate} value={form.endDate} onChange={event => setForm({ ...form, endDate: event.target.value })} /></label></div><label className="reminder-enabled"><input type="checkbox" checked={form.enabled} onChange={event => setForm({ ...form, enabled: event.target.checked })} /> Reminder enabled</label><p className="medicine-form-note">Times are entered by you. Sanjeevani does not calculate medically appropriate medicine timing.</p><button className="button primary" disabled={busy}>{busy ? "Saving reminder…" : "Save Reminder"}</button></form>;
}

function TodayMedicines({ medicines, markTaken, busy }) {
  const date = today(), currentTime = new Date().toTimeString().slice(0, 5);
  const entries = medicines.flatMap(medicine => { const reminder = medicine.reminder; if (!reminder?.enabled || date < reminder.startDate || (reminder.endDate && date > reminder.endDate)) return []; return reminder.times.map(time => ({ medicine, time, taken: reminder.taken?.some(item => item.date === date && item.time === time), missed: time < currentTime })); }).sort((a, b) => a.time.localeCompare(b.time));
  return <section className="medicine-panel today-medicines"><div className="medicine-section-head"><div><span className="section-kicker">TODAY'S MEDICINES</span><h2>Reminder schedule</h2></div><span className="medicine-count">{entries.length} times</span></div>{entries.length ? <div>{entries.map(entry => <article key={`${idOf(entry.medicine)}-${entry.time}`}><time>{timeLabel(entry.time)}</time><div><b>{entry.medicine.title}</b><small>{entry.medicine.formStrength || entry.medicine.dose || "Strength not recorded"}</small></div>{entry.taken ? <span className="taken-status"><Check size={14} /> Taken</span> : <><span className={entry.missed ? "missed-status" : "scheduled-status"}>{entry.missed ? "Missed" : "Scheduled"}</span><button className="button secondary compact" disabled={busy} onClick={() => markTaken(idOf(entry.medicine), { date, time: entry.time })}>Taken</button></>}</article>)}</div> : <div className="medicine-empty">No enabled medicine reminders are scheduled for today.</div>}{entries.some(entry => entry.missed && !entry.taken) && <p className="medicine-form-note">If you're unsure what to do after missing a dose, check your prescription or ask a doctor or pharmacist.</p>}</section>;
}

function MyMedicines({ profile, update, remove, saveReminder, deleteReminder, busy, onPermission }) {
  const medicines = profile.history.filter(item => item.category === "Medicine" && !item.patientProfileId);
  const current = medicines.filter(item => item.status?.toLowerCase() !== "previous"), previous = medicines.filter(item => item.status?.toLowerCase() === "previous");
  const askAbout = title => window.dispatchEvent(new CustomEvent("sanjeevani-ask-medicine", { detail: `Tell me about ${title}.` }));
  const list = (items, empty, reminders = false) => items.length ? <div className="my-medicine-list">{items.map(item => <article key={idOf(item)}><span className="medicine-pill-icon"><Pill size={17} /></span><div className="medicine-record-copy"><b>{item.title}</b><small>{item.formStrength || item.dose || "Strength not recorded"} · Started {dateLabel(item.startDate)}</small>{item.purpose && <p>{item.purpose}</p>}</div><div className="medicine-row-actions"><button className="button secondary compact" onClick={() => askAbout(item.title)}>Ask About This</button>{item.status?.toLowerCase() !== "previous" && <button className="button secondary compact" disabled={busy} onClick={() => update(idOf(item), { status: "Previous", endDate: today() })}>Mark Previous</button>}<button className="icon-button danger" aria-label={`Delete ${item.title}`} onClick={() => window.confirm("Permanently delete this medicine record?") && remove(idOf(item))}><Trash2 size={15} /></button></div>{reminders && <ReminderEditor medicine={item} save={saveReminder} remove={deleteReminder} busy={busy} onPermission={onPermission} />}</article>)}</div> : <div className="medicine-empty">{empty}</div>;
  return <section className="medicine-panel"><div className="medicine-section-head"><div><span className="section-kicker">MY MEDICINES</span><h2>My Medicines</h2></div><span className="medicine-count">{current.length} current</span></div><h3>Current</h3>{list(current, "No current medicines added.", true)}<h3>Previous</h3>{list(previous, "No previous medicine history.")}</section>;
}

function MedicineAssistant({ save, saving }) {
  const [name, setName] = useState(""), [result, setResult] = useState(null), [searching, setSearching] = useState(false), [searchError, setSearchError] = useState("");
  const search = async event => { event.preventDefault(); const value = name.trim(); if (!value) { setSearchError("Enter a medicine name."); return; } setSearching(true); setSearchError(""); setResult(null); try { setResult(await api.medicines.research(value)); } catch (requestError) { setSearchError(requestError.response?.data?.message || "Medicine information is temporarily unavailable. Please try again."); } finally { setSearching(false); } };
  const list = (title, values) => values?.length ? <section><h3>{title}</h3><ul>{values.map(value => <li key={value}>{value}</li>)}</ul></section> : null;
  return <><form className="medicine-search" onSubmit={search}><label htmlFor="medicine-search">Search a medicine to understand its uses, side effects and important precautions.</label><div><Search size={18} /><input id="medicine-search" maxLength="120" value={name} onChange={event => setName(event.target.value)} placeholder="Search medicine name…" /><button className="button primary" disabled={searching}>{searching ? "Finding…" : "Search"}</button></div></form>{searching && <div className="medicine-loading">Finding medicine information…</div>}{searchError && <div className="medicine-error" role="alert"><AlertTriangle size={17} />{searchError}</div>}{result && !result.found && <div className="medicine-error" role="status"><AlertTriangle size={17} />{result.message}</div>}{result?.found && <section className="medicine-panel medicine-ai-result"><span className="section-kicker">MEDICINE INFORMATION</span><h2>{result.displayName || result.genericName}</h2>{result.correctedName && <p><b>Did you mean:</b> {result.correctedName}</p>}<div className="medicine-result-facts">{result.genericName && <p><span>Generic / Salt</span><b>{result.genericName}</b></p>}{result.strength && <p><span>Strength</span><b>{result.strength}</b></p>}{result.drugClass && <p><span>Drug Type</span><b>{result.drugClass}</b></p>}</div>{result.simpleExplanation && <p>{result.simpleExplanation}</p>}{list("Common Uses", result.uses)}{list("Common Side Effects", result.commonSideEffects)}{list("Important Precautions", result.precautions)}{list("Important Warnings", result.importantWarnings)}<button className="button primary" disabled={saving} onClick={() => save({ category: "Medicine", title: result.displayName || result.genericName, formStrength: result.strength, dose: result.strength, purpose: result.simpleExplanation, details: result.genericName ? `Generic: ${result.genericName}` : "", status: "Current", startDate: today() })}><Plus size={15} /> Add to My Medicines</button><small className="medicine-result-disclaimer">Medicine information is for general education and does not replace advice from a doctor or pharmacist.</small></section>}</>;
}

export function MedicineSafety({ onNavigate, user, onRequireAuth }) {
  const [query, setQuery] = useState(""), [results, setResults] = useState([]), [medicine, setMedicine] = useState(null), [profile, setProfile] = useState(null);
  const [searching, setSearching] = useState(false), [loading, setLoading] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState(""), [searched, setSearched] = useState(false), [symptom, setSymptom] = useState(""), [notificationMessage, setNotificationMessage] = useState("");
  const loadProfile = async () => { if (!user) { setProfile(null); return; } try { const data = await api.healthTracker.load(); setProfile({ plans: data.plans || [], history: (data.history || []).filter(item => !item.patientProfileId) }); } catch { setProfile({ plans: [], history: [] }); } };
  useEffect(() => { loadProfile(); }, [user]);
  const search = async event => { event?.preventDefault(); const value = query.trim(); if (value.length < 2) { setError("Enter at least two characters."); return; } setSearching(true); setError(""); setMedicine(null); setSearched(true); try { setResults(await api.medicines.search(value)); } catch (requestError) { setResults([]); setError(requestError.response?.data?.message || "Medicine information could not be loaded."); } finally { setSearching(false); } };
  const select = async result => { setLoading(true); setError(""); setSymptom(""); try { const details = await api.medicines.details(result.id); setMedicine(result.resolution ? { ...details, name: result.resolution.possibleBrand || result.resolution.originalQuery, genericName: medicineName(result.resolution.genericName), searchedStrength: result.resolution.strength, resolvedFromBrand: true } : details); } catch (requestError) { setMedicine(null); setError(requestError.response?.data?.message || "Medicine information could not be loaded."); } finally { setLoading(false); } };
  const saveMedicine = async data => { if (!user) { onRequireAuth(); return false; } setSaving(true); setError(""); try { await api.healthTracker.addHistory(data); await loadProfile(); setSaving(false); return true; } catch (requestError) { setError(requestError.response?.data?.message || "We couldn't save this medicine."); setSaving(false); return false; } };
  const updateMedicine = async (id, data) => { setSaving(true); try { await api.healthTracker.updateHistory(id, data); await loadProfile(); } catch { setError("We couldn't update this medicine."); } finally { setSaving(false); } };
  const removeMedicine = async id => { setSaving(true); try { await api.healthTracker.deleteHistory(id); await loadProfile(); } catch { setError("We couldn't delete this medicine."); } finally { setSaving(false); } };
  const requestNotificationPermission = async () => { if (!("Notification" in window)) { setNotificationMessage("This browser does not support notifications. Your reminder will still appear in Today's Medicines while Sanjeevani is open."); return false; } if (Notification.permission === "granted") return true; if (Notification.permission === "denied") { setNotificationMessage("Notifications are disabled. Enable browser notifications to receive medicine reminders."); return false; } const permission = await Notification.requestPermission(); if (permission !== "granted") setNotificationMessage("Notifications are disabled. Enable browser notifications to receive medicine reminders."); else setNotificationMessage("Browser notifications enabled."); return permission === "granted"; };
  const remindersChanged = () => window.dispatchEvent(new Event("sanjeevani-reminders-changed"));
  const saveReminder = async (id, data) => { setSaving(true); setError(""); try { await api.healthTracker.saveReminder(id, data); await loadProfile(); remindersChanged(); setSaving(false); return true; } catch (requestError) { setError(requestError.response?.data?.message || "We couldn't save this reminder."); setSaving(false); return false; } };
  const deleteReminder = async id => { setSaving(true); try { await api.healthTracker.deleteReminder(id); await loadProfile(); remindersChanged(); } catch { setError("We couldn't delete this reminder."); } finally { setSaving(false); } };
  const markTaken = async (id, data) => { setSaving(true); try { await api.healthTracker.markReminderTaken(id, data); await loadProfile(); remindersChanged(); } catch { setError("We couldn't mark this reminder as taken."); } finally { setSaving(false); } };
  const allergies = profile?.history.filter(item => item.category === "Allergy") || [];
  const currentMedicines = profile?.history.filter(item => item.category === "Medicine" && item.status?.toLowerCase() !== "previous") || [];
  const symptomResult = useMemo(() => { const term = symptom.trim().toLowerCase(); if (term.length < 2 || !medicine?.adverseReactions) return null; return medicine.adverseReactions.toLowerCase().includes(term); }, [symptom, medicine]);
  return <section className="medicine-safety-view"><header className="page-heading medicine-heading"><span className="section-kicker">MEDICINE INFORMATION & REMINDERS</span><h1>Medicines</h1><p>Search a medicine to understand what it is used for, side effects and important precautions.</p></header><MedicineAssistant save={saveMedicine} saving={saving} />{error && <div className="medicine-error" role="alert"><AlertTriangle size={17} />{error}</div>}{notificationMessage && <div className="notification-message" role="status">{notificationMessage}<button onClick={() => setNotificationMessage("")}>Dismiss</button></div>}{profile && <><TodayMedicines medicines={currentMedicines} markTaken={markTaken} busy={saving} /><MyMedicines profile={profile} update={updateMedicine} remove={removeMedicine} saveReminder={saveReminder} deleteReminder={deleteReminder} busy={saving} onPermission={requestNotificationPermission} /></>}</section>;
  /* Legacy exact-label detail flow retained below for internal compatibility, but no longer rendered. */
  /* c8 ignore next */
  return <section className="medicine-safety-view"><header className="page-heading medicine-heading"><span className="section-kicker">MEDICINE INFORMATION & REMINDERS</span><h1>Medicines</h1><p>Search medicines, understand their uses and manage your medicine reminders.</p></header>
    <MedicineAssistant />
    <form className="medicine-search" onSubmit={search}><label htmlFor="medicine-search">Find an official medicine label to save it to My Medicines</label><div><Search size={18} /><input id="medicine-search" maxLength="80" value={query} onChange={event => setQuery(event.target.value)} placeholder="Enter a generic or brand name" /><button className="button primary" disabled={searching}>{searching ? "Searching medicine…" : "Search"}</button></div></form>
    {error && <div className="medicine-error" role="alert"><AlertTriangle size={17} />{error}</div>}
    {notificationMessage && <div className="notification-message" role="status">{notificationMessage.includes("disabled") || notificationMessage.includes("does not support") ? <BellOff size={17} /> : <Bell size={17} />}{notificationMessage}<button onClick={() => setNotificationMessage("")}>Dismiss</button></div>}
    {loading && <div className="medicine-loading" aria-live="polite">Loading safety information…</div>}
    {!loading && !medicine && <>{profile && <TodayMedicines medicines={currentMedicines} markTaken={markTaken} busy={saving} />}<div className="medicine-layout"><section className="medicine-panel"><span className="section-kicker">SEARCH RESULTS</span><h2>{searched ? `Results for “${query.trim()}”` : "Find verified medicine information"}</h2>{searching ? <div className="medicine-empty">Searching medicine…</div> : results.length ? <div className="medicine-results">{results.map(result => <button key={result.id} onClick={() => select(result)}><span className="medicine-pill-icon"><Pill size={18} /></span><span><b>{result.resolution?.possibleBrand || result.name}</b><small>{result.resolution ? `Generic: ${medicineName(result.resolution.genericName)}${result.resolution.strength ? ` · ${result.resolution.strength}` : ""}` : result.genericName || "Generic name not listed"}{!result.resolution && result.manufacturer ? ` · ${result.manufacturer}` : ""}</small></span><ArrowRight size={17} /></button>)}</div> : <div className="medicine-empty">{searched ? `No reliable medicine information was found for “${query.trim()}” after checking brand and generic names.` : "Search for a medicine to view safety information."}</div>}</section>{profile && <MyMedicines profile={profile} update={updateMedicine} remove={removeMedicine} saveReminder={saveReminder} deleteReminder={deleteReminder} busy={saving} onPermission={requestNotificationPermission} />}</div></>}
    {!loading && medicine && <><button className="text-button medicine-back" onClick={() => setMedicine(null)}>← Back to search results</button><section className="medicine-identity"><div className="medicine-hero-icon"><Pill size={27} /></div><div><span className="section-kicker">{medicine.resolvedFromBrand ? "BRAND RESOLVED TO VERIFIED LABEL" : "MEDICINE LABEL"}</span><h2>{medicine.name}</h2>{medicine.genericName && <p><b>Generic medicine:</b> {medicine.genericName}</p>}{medicine.searchedStrength && <p><b>Strength:</b> {medicine.searchedStrength}</p>} {medicine.drugClass.length > 0 && <p><b>Drug class:</b> {medicine.drugClass.join(", ")}</p>} {medicine.manufacturer && <p><b>Label manufacturer:</b> {medicine.manufacturer}</p>}</div><AddMedicineForm medicine={medicine} plans={profile?.plans || []} onSave={saveMedicine} saving={saving} /></section>
      <div className="medicine-detail-grid"><section className="medicine-panel medicine-labels"><span className="section-kicker">OFFICIAL LABEL SECTIONS</span><h2>Medicine information</h2>{!medicine.uses && !medicine.adverseReactions && !medicine.warnings && <div className="medicine-empty">This label does not contain the requested safety sections.</div>}<LabelSection title="Common Uses / Indications" text={medicine.uses} /><LabelSection title="Reported Adverse Reactions" text={medicine.adverseReactions} /><LabelSection title="Important Safety Information" text={medicine.warnings} tone="warning" /><LabelSection title="Contraindications" text={medicine.contraindications} tone="warning" /><LabelSection title="Precautions" text={medicine.precautions} /><LabelSection title="Drug Interaction Information" text={medicine.interactions} tone="warning" /><LabelSection title="Pregnancy / Breastfeeding Information" text={medicine.pregnancy} /></section>
        <aside><section className="medicine-panel"><span className="section-kicker">SIDE-EFFECT SEARCH</span><h2>Are you experiencing a symptom?</h2><label htmlFor="side-effect-search">Compare with this label’s reported adverse-effect text</label><input id="side-effect-search" value={symptom} maxLength="80" onChange={event => setSymptom(event.target.value)} placeholder="For example, nausea" />{symptomResult !== null && <div className={`symptom-result ${symptomResult ? "found" : "not-found"}`}>{symptomResult ? <CheckCircle2 size={17} /> : <AlertTriangle size={17} />}<span><b>{symptomResult ? "Listed in available medicine information" : "Not found in available medicine information"}</b><small>{symptomResult ? "This symptom is listed as a possible reported effect. This does not confirm the medicine caused it." : "This does not rule out a medicine-related effect. Consider asking a doctor or pharmacist."}</small></span></div>}</section>
        <section className="medicine-panel"><span className="section-kicker">CHECK WITH MY HEALTH PROFILE</span><h2>Personal records</h2><div className="profile-stat"><span>Current recorded medicines</span><b>{currentMedicines.length}</b></div><div className="profile-stat"><span>Recorded allergies</span><b>{allergies.length}</b></div>{allergies.length > 0 && <div className="recorded-allergies"><AlertTriangle size={17} /><div><b>Recorded allergies</b><p>{allergies.map(item => item.title).join(", ")}</p><small>Sanjeevani has not inferred a drug-family relationship. Confirm medicine safety with a healthcare professional.</small></div></div>}<p className="medicine-form-note">The FDA label text is shown separately. No automatic interaction or allergy compatibility conclusion is made.</p></section></aside></div>
      <section className="medicine-source"><ShieldAlert size={17} /><div><b>Source transparency</b><p>Medicine information source: <a href={medicine.source.url} target="_blank" rel="noreferrer">{medicine.source.name} <ExternalLink size={12} /></a>. Label sections may vary by product and may use technical language.{medicine.effectiveTime && ` Label effective date: ${medicine.effectiveTime}.`}</p></div></section><section className="medicine-emergency"><AlertTriangle size={20} /><div><b>Severe reaction or emergency?</b><p>If you believe you are having a severe allergic reaction or another medical emergency, seek emergency medical help immediately.</p></div><button className="button secondary" onClick={() => onNavigate("SOS Response")}>Emergency SOS</button></section></>}
  </section>;
}
