import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ChevronLeft, ChevronRight, Pencil, Trash2 } from "lucide-react";
import { api } from "../../services/api";
import { addDays, calculateCycleStatistics, daysBetween, estimateNextPeriod, formatDateOnly, localToday, parseDateOnly, sortedCycles } from "../../services/cycleCalculations";

const idOf = item => item?._id || item?.id;
const dateLabel = value => value ? parseDateOnly(value).toLocaleDateString(undefined, { timeZone: "UTC", day: "numeric", month: "short", year: "numeric" }) : "—";
const symptoms = ["Cramps", "Bloating", "Headache", "Fatigue", "Back Pain", "Nausea", "Acne", "Breast Tenderness"];

function PeriodEditor({ cycles, save, update, remove, busy, onClose }) {
  const empty = { startDate: localToday(), endDate: "", notes: "" };
  const [form, setForm] = useState(empty), [editing, setEditing] = useState(null);
  const submit = async event => { event.preventDefault(); const ok = editing ? await update(idOf(editing), form) : await save(form); if (ok) { setForm(empty); setEditing(null); } };
  return <section className="women-panel"><div className="women-section-head"><div><span className="section-kicker">PERIOD CALENDAR</span><h2>{editing ? "Edit period" : "Add a period"}</h2></div><button className="text-button" onClick={onClose}>Close</button></div><form onSubmit={submit}><div className="women-form-grid"><label>Period start date<input required type="date" max={localToday()} value={form.startDate} onChange={event => setForm({ ...form, startDate: event.target.value })} /></label><label>Period end date<input type="date" min={form.startDate} max={localToday()} value={form.endDate} onChange={event => setForm({ ...form, endDate: event.target.value })} /></label></div><button className="button primary" disabled={busy}>{busy ? "Saving…" : editing ? "Update period" : "Save period"}</button>{editing && <button type="button" className="button secondary" onClick={() => { setEditing(null); setForm(empty); }}>Cancel edit</button>}</form><div className="cycle-record-list">{[...cycles].sort((a, b) => b.startDate.localeCompare(a.startDate)).map(cycle => <article key={idOf(cycle)}><div><b>{dateLabel(cycle.startDate)}{cycle.endDate ? ` – ${dateLabel(cycle.endDate)}` : ""}</b><small>{cycle.endDate ? `Period duration: ${daysBetween(cycle.startDate, cycle.endDate) + 1} days` : "End date not recorded"}</small></div><div><button className="icon-button" aria-label="Edit period" onClick={() => { setEditing(cycle); setForm({ startDate: cycle.startDate, endDate: cycle.endDate || "", notes: cycle.notes || "" }); }}><Pencil size={15} /></button><button className="icon-button danger" aria-label="Delete period" onClick={() => window.confirm("Delete this period record?") && remove(idOf(cycle))}><Trash2 size={15} /></button></div></article>)}</div></section>;
}

function Calendar({ cycles, estimate, averagePeriod }) {
  const latest = sortedCycles(cycles).at(-1), initial = parseDateOnly(latest?.startDate || localToday());
  const [month, setMonth] = useState(new Date(Date.UTC(initial.getUTCFullYear(), initial.getUTCMonth(), 1)));
  const year = month.getUTCFullYear(), monthIndex = month.getUTCMonth(), firstDay = new Date(Date.UTC(year, monthIndex, 1)).getUTCDay(), totalDays = new Date(Date.UTC(year, monthIndex + 1, 0)).getUTCDate();
  const recorded = new Set(cycles.flatMap(cycle => Array.from({ length: cycle.endDate ? Math.min(30, daysBetween(cycle.startDate, cycle.endDate) + 1) : 1 }, (_, index) => addDays(cycle.startDate, index))));
  const estimateDuration = Math.max(1, Math.round(averagePeriod || 5));
  const estimated = new Set(estimate.date ? Array.from({ length: estimateDuration }, (_, index) => addDays(estimate.date, index)) : []);
  const cells = [...Array(firstDay).fill(null), ...Array.from({ length: totalDays }, (_, index) => formatDateOnly(new Date(Date.UTC(year, monthIndex, index + 1))))];
  return <section className="women-panel"><div className="calendar-head"><button className="icon-button" aria-label="Previous month" onClick={() => setMonth(new Date(Date.UTC(year, monthIndex - 1, 1)))}><ChevronLeft /></button><h2>{month.toLocaleDateString(undefined, { timeZone: "UTC", month: "long", year: "numeric" })}</h2><button className="icon-button" aria-label="Next month" onClick={() => setMonth(new Date(Date.UTC(year, monthIndex + 1, 1)))}><ChevronRight /></button></div><div className="calendar-legend"><span><i className="recorded" /> Recorded Period</span><span><i className="estimated" /> Estimated Period</span></div><div className="cycle-calendar" role="grid">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map(day => <b role="columnheader" key={day}>{day}</b>)}{cells.map((date, index) => date ? <div role="gridcell" key={date} className={`${recorded.has(date) ? "recorded" : ""} ${estimated.has(date) && !recorded.has(date) ? "estimated" : ""}`} aria-label={`${date}${recorded.has(date) ? ", recorded period" : estimated.has(date) ? ", estimated period" : ""}`}><span>{Number(date.slice(-2))}</span></div> : <div key={`blank-${index}`} />)}</div></section>;
}

function TodayLog({ logs, save, busy, onClose }) {
  const existing = logs.find(log => log.date === localToday());
  const [form, setForm] = useState(() => ({ date: localToday(), flow: existing?.flow || "", pain: existing?.pain ?? "", mood: existing?.mood || "", energy: existing?.energy || "", symptoms: existing?.symptoms || [], notes: existing?.notes || "" }));
  const toggle = value => setForm(current => ({ ...current, symptoms: current.symptoms.includes(value) ? current.symptoms.filter(item => item !== value) : [...current.symptoms, value] }));
  const painOptions = [[0, "None"], [3, "Mild"], [6, "Moderate"], [9, "Severe"]];
  return <section className="women-panel"><div className="women-section-head"><div><span className="section-kicker">TODAY'S HEALTH LOG</span><h2>Log Today</h2></div><button className="text-button" onClick={onClose}>Close</button></div><form onSubmit={event => { event.preventDefault(); save(form); }}><fieldset><legend>Period Flow</legend><div className="women-segmented">{[["No period", "None"], ["Light", "Light"], ["Medium", "Medium"], ["Heavy", "Heavy"]].map(([value, label]) => <button type="button" key={value} className={form.flow === value ? "active" : ""} onClick={() => setForm({ ...form, flow: value })}>{label}</button>)}</div></fieldset><fieldset><legend>Pain / Cramps</legend><div className="women-segmented">{painOptions.map(([value, label]) => <button type="button" key={value} className={form.pain === value ? "active" : ""} onClick={() => setForm({ ...form, pain: value })}>{label}</button>)}</div></fieldset><div className="women-form-grid"><label>Mood<select value={form.mood} onChange={event => setForm({ ...form, mood: event.target.value })}><option value="">Choose</option><option>Low</option><option value="Neutral">Normal</option><option>Good</option></select></label><label>Energy<select value={form.energy} onChange={event => setForm({ ...form, energy: event.target.value })}><option value="">Choose</option><option>Low</option><option>Normal</option><option>High</option></select></label></div><fieldset><legend>Symptoms</legend><div className="women-choice-grid symptoms">{symptoms.map(value => <label key={value}><input type="checkbox" checked={form.symptoms.includes(value)} onChange={() => toggle(value)} /> {value}</label>)}</div></fieldset><label>Notes (optional)<textarea maxLength="2000" placeholder="More cramps in the morning." value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} /></label><button className="button primary" disabled={busy}>{busy ? "Saving…" : existing ? "Update today's log" : "Save"}</button></form></section>;
}

function History({ cycles, stats }) {
  const chart = stats.lengths.slice(-8), max = Math.max(...chart.map(item => item.days), 1);
  return <section className="women-panel"><span className="section-kicker">CYCLE HISTORY</span><h2>Cycle Length</h2>{chart.length ? <div className="women-chart" role="img" aria-label="Cycle length by month"><svg viewBox="0 0 360 170" preserveAspectRatio="none"><line x1="20" y1="140" x2="345" y2="140" />{chart.map((item, index) => { const width = 320 / chart.length, height = item.days / max * 105; return <g key={item.startDate}><rect x={23 + index * width} y={140 - height} width={Math.max(12, width - 12)} height={height} rx="4"><title>{dateLabel(item.startDate)}: {item.days} days</title></rect><text x={23 + index * width + Math.max(12, width - 12) / 2} y="157" textAnchor="middle">{parseDateOnly(item.startDate).toLocaleDateString(undefined, { timeZone: "UTC", month: "short" })}</text></g>; })}</svg></div> : <div className="women-empty">Record at least two periods to see cycle length.</div>}<div className="women-stat-list"><p><span>Average Cycle</span><b>{stats.averageCycle ? `${stats.averageCycle.toFixed(1)} days` : "Not enough data"}</b></p><p><span>Shortest</span><b>{stats.shortest ? `${stats.shortest} days` : "—"}</b></p><p><span>Longest</span><b>{stats.longest ? `${stats.longest} days` : "—"}</b></p></div><div className="cycle-record-list">{[...cycles].sort((a, b) => b.startDate.localeCompare(a.startDate)).map((cycle, index, ordered) => { const older = ordered[index + 1], length = older ? daysBetween(older.startDate, cycle.startDate) : null; return <article key={idOf(cycle)}><div><b>{dateLabel(cycle.startDate)}{cycle.endDate ? ` – ${dateLabel(cycle.endDate)}` : ""}</b><small>{cycle.endDate ? `Period Duration: ${daysBetween(cycle.startDate, cycle.endDate) + 1} days` : "Period end not recorded"}{length ? ` · Cycle Length: ${length} days` : ""}</small></div></article>; })}</div></section>;
}

export function WomensHealth() {
  const [profile, setProfile] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(""), [open, setOpen] = useState(null);
  const load = async () => { try { setProfile(await api.healthTracker.load()); } catch { setError("We couldn't load your women's health records."); } };
  useEffect(() => { load(); }, []);
  const mutate = async (method, ...args) => { setBusy(true); setError(""); try { await api.womensHealth[method](...args); await load(); return true; } catch (requestError) { setError(requestError.response?.data?.message || "We couldn't save that record."); return false; } finally { setBusy(false); } };
  const data = profile?.womensHealth || { cycles: [], dailyLogs: [] }, cycles = data.cycles || [], logs = data.dailyLogs || [], stats = useMemo(() => calculateCycleStatistics(cycles, logs), [cycles, logs]);
  if (!profile) return <section className="women-loading">Loading private health records…</section>;
  const estimate = estimateNextPeriod(cycles), latest = sortedCycles(cycles).at(-1), cycleDay = latest ? daysBetween(latest.startDate, localToday()) + 1 : null;
  const symptomCounts = Object.entries(stats.symptomCounts).sort((a, b) => b[1] - a[1]);
  return <section className="womens-health-view"><header className="page-heading women-heading"><span className="section-kicker">PRIVATE CYCLE TRACKING</span><h1>Women's Health</h1><p>A simple place to track periods, daily symptoms, and cycle changes.</p></header>{error && <div className="women-error" role="alert"><AlertTriangle size={17} />{error}</div>}<div className="women-overview-grid"><article><span>Current Cycle</span><b>{cycleDay > 0 ? `Day ${cycleDay}` : "—"}</b><small>{latest ? `Started ${dateLabel(latest.startDate)}` : "No recorded period"}</small></article><article><span>Next Period</span><b>{estimate.date ? `Around ${dateLabel(estimate.date)}` : "Not available"}</b><small>{estimate.date ? "Estimated from your recorded cycles" : "Record more cycles to estimate your next period."}</small></article><article><span>Average Cycle</span><b>{stats.averageCycle ? `${stats.averageCycle.toFixed(1)} days` : "—"}</b><small>{stats.averageCycle ? "Based on recorded periods" : "Not enough data"}</small></article></div><Calendar cycles={cycles} estimate={estimate} averagePeriod={stats.averagePeriod} /><div className="women-form-actions"><button className="button primary" onClick={() => setOpen(open === "log" ? null : "log")}>+ Log Today</button><button className="button secondary" onClick={() => setOpen(open === "period" ? null : "period")}>+ Add Period</button></div>{open === "log" && <TodayLog logs={logs} save={form => mutate("saveLog", form)} busy={busy} onClose={() => setOpen(null)} />}{open === "period" && <PeriodEditor cycles={cycles} save={form => mutate("addCycle", form)} update={(id, form) => mutate("updateCycle", id, form)} remove={id => mutate("deleteCycle", id)} busy={busy} onClose={() => setOpen(null)} />}<History cycles={cycles} stats={stats} /><section className="women-panel"><span className="section-kicker">RECORDED PATTERNS ONLY</span><h2>Your Common Symptoms</h2>{symptomCounts.length ? <div className="symptom-frequency">{symptomCounts.slice(0, 8).map(([name, count]) => <p key={name}><span>{name}</span><b>{count} {count === 1 ? "time" : "times"}</b></p>)}</div> : <div className="women-empty">No symptoms recorded yet.</div>}<p className="women-estimate-note">This only summarizes what you recorded and is not a diagnosis.</p></section></section>;
}
