import { useEffect, useMemo, useState } from "react";
import { Activity, Archive, Check, ChevronRight, Copy, HeartPulse, Info, Pencil, Plus, Printer, Trash2 } from "lucide-react";
import { api } from "../../services/api";

const TODAY = () => new Date().toISOString().slice(0, 10);
const idOf = item => item?._id || item?.id;
const dateLabel = value => value ? new Date(value).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" }) : "—";
const number = value => Number.isFinite(Number(value)) ? Number(value) : null;
const valuesOf = checkIn => checkIn?.values instanceof Map ? Object.fromEntries(checkIn.values) : checkIn?.values || {};

const PRESETS = {
  "Post-Surgery Recovery": [["pain", "Pain", "/10", "scale", "lower"], ["mobility", "Mobility", "/10", "scale", "higher"], ["swelling", "Swelling", "/10", "scale", "lower"], ["energy", "Energy", "/10", "scale", "higher"], ["sleep", "Sleep", "/10", "scale", "higher"], ["appetite", "Appetite", "/10", "scale", "higher"], ["physiotherapy", "Physical therapy completed", "", "boolean", "higher"], ["medicine", "Medicine adherence", "", "boolean", "higher"], ["temperature", "Temperature", "°C", "number", "neutral"]],
  "Illness Recovery": [["symptoms", "Symptom severity", "/10", "scale", "lower"], ["pain", "Pain", "/10", "scale", "lower"], ["fatigue", "Fatigue", "/10", "scale", "lower"], ["energy", "Energy", "/10", "scale", "higher"], ["appetite", "Appetite", "/10", "scale", "higher"], ["hydration", "Hydration", "/10", "scale", "higher"], ["sleep", "Sleep", "/10", "scale", "higher"], ["temperature", "Temperature", "°C", "number", "neutral"], ["medicine", "Medicines taken", "", "boolean", "higher"]],
  "Injury Recovery": [["pain", "Pain", "/10", "scale", "lower"], ["swelling", "Swelling", "/10", "scale", "lower"], ["movement", "Movement", "/10", "scale", "higher"], ["mobility", "Mobility", "/10", "scale", "higher"], ["strength", "Strength", "/10", "scale", "higher"], ["physiotherapy", "Physiotherapy completed", "", "boolean", "higher"], ["activity", "Activity", "/10", "scale", "higher"]],
  "Chronic Condition": [["systolic", "Blood pressure (systolic)", "mmHg", "number", "neutral"], ["diastolic", "Blood pressure (diastolic)", "mmHg", "number", "neutral"], ["glucose", "Blood glucose", "mg/dL", "number", "neutral"], ["heartRate", "Heart rate", "bpm", "number", "neutral"], ["spo2", "SpO₂", "%", "number", "neutral"], ["weight", "Weight", "kg", "number", "neutral"], ["sleep", "Sleep", "/10", "scale", "higher"], ["symptoms", "Symptom severity", "/10", "scale", "lower"], ["medicine", "Medication adherence", "", "boolean", "higher"], ["activity", "Activity", "/10", "scale", "higher"]],
  "General Health": [["energy", "Energy", "/10", "scale", "higher"], ["sleep", "Sleep", "/10", "scale", "higher"], ["appetite", "Appetite", "/10", "scale", "higher"], ["activity", "Activity", "/10", "scale", "higher"], ["symptoms", "Symptom severity", "/10", "scale", "lower"]],
  Custom: []
};

const metricFromPreset = ([key, label, unit, inputType, direction]) => ({ key, label, unit, inputType, direction, min: inputType === "scale" ? 0 : 0, max: inputType === "scale" ? 10 : 100, baseline: inputType === "boolean" ? false : 0 });
const emptyPlan = () => ({ type: "Post-Surgery Recovery", title: "", conditionName: "", startDate: TODAY(), description: "", hospital: "", doctor: "", goal: "", targetDate: "", metrics: PRESETS["Post-Surgery Recovery"].slice(0, 4).map(metricFromPreset) });

function trendFor(plan) {
  const points = [...(plan?.checkIns || [])].filter(item => number(item.opi) !== null).sort((a, b) => new Date(a.date) - new Date(b.date));
  if (points.length < 2) return "Insufficient Data";
  const delta = points.at(-1).opi - points[Math.max(0, points.length - 4)].opi;
  if (delta >= 5) return "Improving";
  if (delta <= -5) return "Needs Attention";
  const metricDirections = plan.metrics.filter(metric => metric.direction !== "neutral");
  const changes = metricDirections.map(metric => {
    const first = number(valuesOf(points[Math.max(0, points.length - 4)])[metric.key]);
    const last = number(valuesOf(points.at(-1))[metric.key]);
    return first === null || last === null ? 0 : (last - first) * (metric.direction === "lower" ? -1 : 1);
  }).filter(Boolean);
  if (changes.some(value => value > 0) && changes.some(value => value < 0)) return "Mixed";
  return "Stable";
}

function LineChart({ points, label, unit = "", valueKey = "opi" }) {
  if (points.length < 2) return <div className="tracker-empty">Add at least two check-ins to see your progress graph.</div>;
  const values = points.map(point => Number(point[valueKey]));
  const low = Math.min(...values), high = Math.max(...values), spread = high - low || 1;
  const coords = points.map((point, index) => `${20 + (index / (points.length - 1)) * 360},${130 - ((Number(point[valueKey]) - low) / spread) * 105}`).join(" ");
  const gradientId = `health-gradient-${valueKey}`;
  return <div className="health-chart" aria-label={`${label} line chart`} role="img"><svg viewBox="0 0 400 160" preserveAspectRatio="none"><defs><linearGradient id={gradientId} x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stopColor="#d9911e" /><stop offset="48%" stopColor="#9fbd3f" /><stop offset="100%" stopColor="#228557" /></linearGradient></defs><line x1="20" x2="380" y1="130" y2="130" /><polyline points={coords} style={{ stroke: `url(#${gradientId})` }} />{points.map((point, index) => { const [x, y] = coords.split(" ")[index].split(","); return <circle key={`${point.date}-${index}`} cx={x} cy={y} r="4"><title>{dateLabel(point.date)} — {label}: {point[valueKey]}{unit}{point.notes ? ` — ${point.notes}` : ""}</title></circle>; })}</svg><div className="chart-range"><span>{dateLabel(points[0].date)}</span><b>{low}{unit} – {high}{unit}</b><span>{dateLabel(points.at(-1).date)}</span></div></div>;
}

function PlanSetup({ onSave, onCancel, busy }) {
  const [form, setForm] = useState(emptyPlan);
  const [custom, setCustom] = useState({ label: "", unit: "", inputType: "number", direction: "higher", min: 0, max: 100, baseline: 0 });
  const changeType = type => setForm(current => ({ ...current, type, metrics: PRESETS[type].slice(0, 4).map(metricFromPreset) }));
  const toggleMetric = definition => setForm(current => { const metric = metricFromPreset(definition); const exists = current.metrics.some(item => item.key === metric.key); return { ...current, metrics: exists ? current.metrics.filter(item => item.key !== metric.key) : [...current.metrics, metric] }; });
  const addCustom = () => { if (!custom.label.trim()) return; const key = `custom-${Date.now()}`; setForm(current => ({ ...current, metrics: [...current.metrics, { ...custom, key, baseline: custom.inputType === "boolean" ? false : Number(custom.baseline) }] })); setCustom({ label: "", unit: "", inputType: "number", direction: "higher", min: 0, max: 100, baseline: 0 }); };
  return <section className="tracker-panel setup-panel"><div className="tracker-panel-head"><div><span className="section-kicker">NEW TRACKING PLAN</span><h2>Start health tracking</h2></div>{onCancel && <button className="text-button" onClick={onCancel}>Cancel</button>}</div><form onSubmit={event => { event.preventDefault(); onSave(form); }}>
    <div className="form-grid"><label>Tracking type<select value={form.type} onChange={event => changeType(event.target.value)}>{Object.keys(PRESETS).map(type => <option key={type}>{type}</option>)}</select></label><label>Tracking title<input required maxLength="160" value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /></label><label>Condition / surgery / illness name<input required maxLength="160" value={form.conditionName} onChange={event => setForm({ ...form, conditionName: event.target.value })} /></label><label>Start date<input type="date" required value={form.startDate} onChange={event => setForm({ ...form, startDate: event.target.value })} /></label><label>Hospital (optional)<input maxLength="160" value={form.hospital} onChange={event => setForm({ ...form, hospital: event.target.value })} /></label><label>Doctor (optional)<input maxLength="160" value={form.doctor} onChange={event => setForm({ ...form, doctor: event.target.value })} /></label><label className="wide">Recovery / health goal<textarea required maxLength="500" value={form.goal} onChange={event => setForm({ ...form, goal: event.target.value })} /></label><label>Target date (optional)<input type="date" value={form.targetDate} onChange={event => setForm({ ...form, targetDate: event.target.value })} /></label><label className="wide">Description (optional)<textarea maxLength="2000" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /></label></div>
    {PRESETS[form.type].length > 0 && <fieldset><legend>Choose the metrics you want to track</legend><div className="metric-choices">{PRESETS[form.type].map(definition => <label key={definition[0]}><input type="checkbox" checked={form.metrics.some(item => item.key === definition[0])} onChange={() => toggleMetric(definition)} /> {definition[1]}</label>)}</div></fieldset>}
    <fieldset><legend>Add a custom metric</legend><div className="custom-metric-row"><input aria-label="Custom metric name" placeholder="Metric name" value={custom.label} onChange={event => setCustom({ ...custom, label: event.target.value })} /><input aria-label="Unit" placeholder="Unit" value={custom.unit} onChange={event => setCustom({ ...custom, unit: event.target.value })} /><select aria-label="Input type" value={custom.inputType} onChange={event => setCustom({ ...custom, inputType: event.target.value })}><option value="number">Number</option><option value="scale">0–10 scale</option><option value="boolean">Yes / No</option></select><select aria-label="Progress direction" value={custom.direction} onChange={event => setCustom({ ...custom, direction: event.target.value })}><option value="higher">Higher is better</option><option value="lower">Lower is better</option><option value="neutral">Neutral</option></select><button type="button" className="button secondary" onClick={addCustom}><Plus size={15} /> Add</button></div></fieldset>
    <fieldset><legend>Starting baseline</legend><p className="field-help">These permanent starting values are used for future comparisons.</p><div className="baseline-grid">{form.metrics.map(metric => <label key={metric.key}>{metric.label}{metric.inputType === "boolean" ? <select value={String(metric.baseline)} onChange={event => setForm({ ...form, metrics: form.metrics.map(item => item.key === metric.key ? { ...item, baseline: event.target.value === "true" } : item) })}><option value="true">Yes</option><option value="false">No</option></select> : <input required type="number" step="any" min={metric.inputType === "scale" ? 0 : undefined} max={metric.inputType === "scale" ? 10 : undefined} value={metric.baseline} onChange={event => setForm({ ...form, metrics: form.metrics.map(item => item.key === metric.key ? { ...item, baseline: event.target.value, min: item.inputType === "scale" ? 0 : Math.min(0, Number(event.target.value)), max: item.inputType === "scale" ? 10 : Math.max(100, Number(event.target.value) * 2 || 100) } : item) })} />}</label>)}</div></fieldset>
    <button className="button primary" disabled={busy || !form.metrics.length}>{busy ? "Saving…" : "Save tracking plan"} <ChevronRight size={16} /></button>
  </form></section>;
}

function CheckInForm({ plan, onSave, busy }) {
  const [form, setForm] = useState({ date: TODAY(), values: {}, notes: "" });
  return <form className="tracker-panel" onSubmit={event => { event.preventDefault(); onSave(form).then(ok => ok && setForm({ date: TODAY(), values: {}, notes: "" })); }}><div className="tracker-panel-head"><div><span className="section-kicker">DAILY RECORD</span><h2>Today’s check-in</h2></div><label className="compact-label">Date<input type="date" required value={form.date} onChange={event => setForm({ ...form, date: event.target.value })} /></label></div><div className="checkin-grid">{plan.metrics.map(metric => <label key={metric.key}><span>{metric.label} <small>{metric.unit}</small></span>{metric.inputType === "boolean" ? <select value={form.values[metric.key] ?? ""} onChange={event => setForm({ ...form, values: { ...form.values, [metric.key]: event.target.value === "true" } })}><option value="">Not recorded</option><option value="true">Yes</option><option value="false">No</option></select> : metric.inputType === "scale" ? <><input type="range" min="0" max="10" value={form.values[metric.key] ?? 5} onChange={event => setForm({ ...form, values: { ...form.values, [metric.key]: Number(event.target.value) } })} /><output>{form.values[metric.key] ?? "—"}/10</output></> : <input type="number" step="any" placeholder="Not recorded" value={form.values[metric.key] ?? ""} onChange={event => setForm({ ...form, values: { ...form.values, [metric.key]: event.target.value } })} />}</label>)}</div><label>Notes<textarea maxLength="2000" placeholder="Walking felt easier today." value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} /></label><button className="button primary" disabled={busy || !Object.keys(form.values).length}>{busy ? "Saving…" : "Save check-in"}</button></form>;
}

function Milestones({ plan, mutate, busy }) {
  const [form, setForm] = useState({ title: "", date: TODAY(), note: "", status: "Upcoming" });
  const save = async event => { event.preventDefault(); if (await mutate("addMilestone", [idOf(plan), form])) setForm({ title: "", date: TODAY(), note: "", status: "Upcoming" }); };
  return <section className="tracker-panel"><div className="tracker-panel-head"><div><span className="section-kicker">RECOVERY MEMORY</span><h2>Recovery milestones</h2></div></div><div className="milestone-list">{(plan.milestones || []).map(item => <article key={idOf(item)}><span className={`milestone-mark ${item.status === "Completed" ? "done" : ""}`}>{item.status === "Completed" ? <Check size={14} /> : "○"}</span><div><b>{item.title}</b><small>{dateLabel(item.date)} · {item.status}</small>{item.note && <p>{item.note}</p>}</div><div className="row-actions"><button className="icon-button" aria-label={`Edit ${item.title}`} onClick={() => { const title = window.prompt("Milestone title", item.title); if (!title) return; const note = window.prompt("Milestone note", item.note || ""); if (note !== null) mutate("updateMilestone", [idOf(plan), idOf(item), { title, note }]); }}><Pencil size={15} /></button><button className="icon-button" aria-label={`Change ${item.title} status`} onClick={() => mutate("updateMilestone", [idOf(plan), idOf(item), { status: item.status === "Completed" ? "In Progress" : "Completed" }])}><Check size={16} /></button><button className="icon-button danger" aria-label={`Delete ${item.title}`} onClick={() => window.confirm("Delete this milestone?") && mutate("deleteMilestone", [idOf(plan), idOf(item)])}><Trash2 size={15} /></button></div></article>)}</div><form className="inline-form" onSubmit={save}><input required maxLength="160" aria-label="Milestone title" placeholder="Add milestone" value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /><input required aria-label="Milestone date" type="date" value={form.date} onChange={event => setForm({ ...form, date: event.target.value })} /><select aria-label="Milestone status" value={form.status} onChange={event => setForm({ ...form, status: event.target.value })}><option>Completed</option><option>In Progress</option><option>Upcoming</option></select><input maxLength="1000" aria-label="Milestone note" placeholder="Optional note" value={form.note} onChange={event => setForm({ ...form, note: event.target.value })} /><button className="button secondary" disabled={busy}><Plus size={15} /> Add</button></form></section>;
}

function MedicalHistory({ profile, mutate, busy }) {
  const [form, setForm] = useState({ category: "Condition", title: "", startDate: "", endDate: "", status: "", details: "", hospital: "", doctor: "", dose: "", frequency: "", reaction: "" });
  const submit = async event => { event.preventDefault(); if (await mutate("addHistory", [form])) setForm({ category: "Condition", title: "", startDate: "", endDate: "", status: "", details: "", hospital: "", doctor: "", dose: "", frequency: "", reaction: "" }); };
  return <div className="tracker-columns"><section className="tracker-panel"><span className="section-kicker">PATIENT MEDICAL MEMORY</span><h2>Medical history</h2>{!profile.history.length ? <div className="tracker-empty">No medical history recorded yet.</div> : <div className="history-list">{profile.history.map(item => <article key={idOf(item)}><span>{item.category}</span><div><b>{item.title}</b><small>{dateLabel(item.startDate)}{item.endDate ? ` – ${dateLabel(item.endDate)}` : ""}{item.status ? ` · ${item.status}` : ""}</small><p>{[item.details, item.dose, item.frequency, item.reaction].filter(Boolean).join(" · ")}</p></div><div className="row-actions"><button className="icon-button" aria-label={`Edit ${item.title}`} onClick={() => { const title = window.prompt("Record name", item.title); if (!title) return; const details = window.prompt("Notes", item.details || ""); if (details !== null) mutate("updateHistory", [idOf(item), { title, details }]); }}><Pencil size={15} /></button><button className="icon-button danger" aria-label={`Delete ${item.title}`} onClick={() => window.confirm("Delete this medical history item?") && mutate("deleteHistory", [idOf(item)])}><Trash2 size={15} /></button></div></article>)}</div>}</section><form className="tracker-panel" onSubmit={submit}><span className="section-kicker">ADD RECORD</span><h2>Remember a health event</h2><div className="form-grid"><label>Category<select value={form.category} onChange={event => setForm({ ...form, category: event.target.value })}>{["Condition", "Surgery", "Illness", "Allergy", "Medicine"].map(value => <option key={value}>{value}</option>)}</select></label><label>Name<input required maxLength="160" value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /></label>{form.category !== "Allergy" && <><label>Start / date<input type="date" value={form.startDate} onChange={event => setForm({ ...form, startDate: event.target.value })} /></label><label>End (optional)<input type="date" value={form.endDate} onChange={event => setForm({ ...form, endDate: event.target.value })} /></label></>}<label>Status<input maxLength="80" value={form.status} onChange={event => setForm({ ...form, status: event.target.value })} /></label>{form.category === "Allergy" && <label>Reaction<input maxLength="500" value={form.reaction} onChange={event => setForm({ ...form, reaction: event.target.value })} /></label>}{form.category === "Medicine" && <><label>Dose<input maxLength="100" value={form.dose} onChange={event => setForm({ ...form, dose: event.target.value })} /></label><label>Frequency<input maxLength="100" value={form.frequency} onChange={event => setForm({ ...form, frequency: event.target.value })} /></label></>}<label className="wide">Notes<textarea maxLength="2000" value={form.details} onChange={event => setForm({ ...form, details: event.target.value })} /></label></div><button className="button primary" disabled={busy}>Save medical record</button></form></div>;
}

function Timeline({ profile }) {
  const [filter, setFilter] = useState("All");
  const events = useMemo(() => {
    const history = profile.history.flatMap(item => [{ date: item.startDate || item.createdAt, type: item.category, title: item.category === "Medicine" ? `${item.title} started` : item.title, detail: item.status || item.details }, ...(item.category === "Medicine" && item.endDate ? [{ date: item.endDate, type: "Medicine", title: `${item.title} marked previous`, detail: item.purpose || item.details }] : [])]);
    const plans = profile.plans.flatMap(plan => [{ date: plan.startDate, type: "Recovery", title: `${plan.title} started`, detail: plan.conditionName }, ...(plan.checkIns || []).map(item => ({ date: item.date, type: "Recovery", title: `Check-in${number(item.opi) !== null ? ` · OPI ${item.opi}` : ""}`, detail: item.notes })), ...(plan.milestones || []).map(item => ({ date: item.date, type: "Milestone", title: item.title, detail: item.status }))]);
    const women = profile.womensHealth || {};
    const womenEvents = [...(women.cycles || []).flatMap(cycle => [{ date: cycle.startDate, type: "Women's Health", title: "Period started", detail: cycle.notes }, ...(cycle.endDate ? [{ date: cycle.endDate, type: "Women's Health", title: "Period ended", detail: "Recorded cycle event" }] : [])]), ...(women.conditions || []).map(item => ({ date: item.diagnosedDate || item.createdAt, type: "Women's Health", title: `Diagnosed condition: ${item.title}`, detail: item.status || item.notes })), ...(women.appointments || []).map(item => ({ date: item.date, type: "Women's Health", title: item.title, detail: [item.doctor, item.hospital].filter(Boolean).join(" · ") }))];
    return [...history, ...plans, ...womenEvents].filter(item => item.date && (filter === "All" || item.type === filter || (filter === "Surgery" && item.type === "Surgery") || (filter === "Medicine" && item.type === "Medicine"))).sort((a, b) => new Date(b.date) - new Date(a.date));
  }, [profile, filter]);
  return <section className="tracker-panel"><div className="tracker-panel-head"><div><span className="section-kicker">LONG-TERM RECORD</span><h2>Medical timeline</h2></div><div className="filter-row">{["All", "Condition", "Surgery", "Illness", "Medicine", "Recovery", "Milestone", "Women's Health"].map(value => <button key={value} className={filter === value ? "active" : ""} onClick={() => setFilter(value)}>{value}</button>)}</div></div>{events.length ? <div className="timeline">{events.map((item, index) => <article key={`${item.date}-${item.title}-${index}`}><time>{dateLabel(item.date)}</time><i /><div><small>{item.type}</small><b>{item.title}</b>{item.detail && <p>{item.detail}</p>}</div></article>)}</div> : <div className="tracker-empty">No timeline events match this filter.</div>}</section>;
}

function DoctorSummary({ plan, profile }) {
  const sorted = [...(plan.checkIns || [])].sort((a, b) => new Date(a.date) - new Date(b.date));
  const latest = sorted.at(-1);
  const text = [`HEALTH TRACKING SUMMARY`, `Tracking: ${plan.title}`, `Condition/event: ${plan.conditionName}`, `Started: ${dateLabel(plan.startDate)}`, `Current through: ${dateLabel(latest?.date || plan.completedAt || new Date())}`, "", "RECORDED CHANGES", ...plan.metrics.map(metric => `${metric.label}: ${metric.baseline}${metric.unit} → ${valuesOf(latest)[metric.key] ?? "not recorded"}${metric.unit}`), "", "MILESTONES", ...(plan.milestones.length ? plan.milestones.map(item => `- ${item.title} (${item.status}, ${dateLabel(item.date)})`) : ["None recorded"]), "", "CURRENT MEDICINES", ...((profile.history.filter(item => item.category === "Medicine" && item.status?.toLowerCase() !== "previous").map(item => `- ${item.title}${item.dose ? `, ${item.dose}` : ""}${item.frequency ? `, ${item.frequency}` : ""}`)) || []), "", "IMPORTANT NOTES", ...(sorted.filter(item => item.notes).slice(-5).map(item => `- ${dateLabel(item.date)}: ${item.notes}`)), "", "This summary organizes patient-recorded information and is not a medical diagnosis."].join("\n");
  return <section className="tracker-panel doctor-summary"><div className="tracker-panel-head"><div><span className="section-kicker">FOR A HEALTHCARE PROFESSIONAL</span><h2>Health summary</h2></div><div className="summary-actions"><button className="button secondary" onClick={() => navigator.clipboard?.writeText(text)}><Copy size={15} /> Copy</button><button className="button secondary" onClick={() => window.print()}><Printer size={15} /> Print</button></div></div><pre>{text}</pre><p className="field-help">The existing Report Simplifier does not store report records, so reports cannot safely be included here.</p></section>;
}

export function HealthTracker({ onNavigate }) {
  const [profile, setProfile] = useState(null), [selectedId, setSelectedId] = useState(null), [tab, setTab] = useState("Overview"), [setup, setSetup] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [range, setRange] = useState("30D"), [metricKey, setMetricKey] = useState("");
  const load = async () => { setError(""); try { const data = await api.healthTracker.load(); setProfile({ plans: data.plans || [], history: (data.history || []).filter(item => !item.patientProfileId), womensHealth: data.womensHealth || {} }); setSelectedId(current => current || idOf(data.plans?.find(plan => plan.status === "active") || data.plans?.[0])); } catch { setError("We couldn't load your health records."); } };
  useEffect(() => { load(); }, []);
  const mutate = async (method, args) => { setBusy(true); setError(""); try { await api.healthTracker[method](...args); await load(); setBusy(false); return true; } catch (requestError) { setError(requestError.response?.data?.message || "We couldn't save that health record."); setBusy(false); return false; } };
  if (!profile) return <section className="tracker-loading" aria-live="polite">{error ? <><p>{error}</p><button className="button primary" onClick={load}>Try Again</button></> : "Loading health records…"}</section>;
  const plan = profile.plans.find(item => idOf(item) === selectedId) || profile.plans[0];
  const active = profile.plans.filter(item => item.status === "active"), past = profile.plans.filter(item => item.status === "completed");
  const latest = [...(plan?.checkIns || [])].sort((a, b) => new Date(b.date) - new Date(a.date))[0];
  const ranges = { "7D": 7, "30D": 30, "3M": 90, "6M": 183, "1Y": 365, All: Infinity };
  const points = [...(plan?.checkIns || [])].filter(item => number(item.opi) !== null && (ranges[range] === Infinity || (Date.now() - new Date(item.date)) / 864e5 <= ranges[range])).sort((a, b) => new Date(a.date) - new Date(b.date));
  const selectedMetric = plan?.metrics.find(metric => metric.key === metricKey) || plan?.metrics[0];
  const metricPoints = [...(plan?.checkIns || [])].map(item => ({ date: item.date, value: valuesOf(item)[selectedMetric?.key], notes: item.notes })).filter(item => number(item.value) !== null && (ranges[range] === Infinity || (Date.now() - new Date(item.date)) / 864e5 <= ranges[range])).sort((a, b) => new Date(a.date) - new Date(b.date));
  const duration = plan ? Math.max(1, Math.ceil((new Date(plan.completedAt || Date.now()) - new Date(plan.startDate)) / 864e5) + 1) : 0;
  const latestOpi = number(latest?.opi);
  const createPlan = async data => { const ok = await mutate("createPlan", [data]); if (ok) setSetup(false); };
  return <section className="health-tracker-view"><header className="page-heading tracker-heading"><span className="section-kicker">YOUR CONTINUOUS HEALTH RECORD</span><h1>Health Tracker</h1><p>Track health and recovery progress over time, while keeping each journey available as part of your medical memory.</p><p className="tracker-disclaimer">Sanjeevani Health Tracker helps organize and visualize health information you record. It does not provide a medical diagnosis or replace professional medical advice.</p></header>
    {error && <div className="tracker-error" role="alert">{error}<button onClick={() => setError("")}>Dismiss</button></div>}
    <div className="tracker-toolbar"><div className="tracker-tabs" role="tablist">{["Overview", "Medical History", "Timeline"].map(value => <button role="tab" aria-selected={tab === value} className={tab === value ? "active" : ""} key={value} onClick={() => setTab(value)}>{value}</button>)}</div><button className="button primary" onClick={() => setSetup(true)}><Plus size={16} /> Start Health Tracking</button></div>
    {setup && <PlanSetup onSave={createPlan} onCancel={() => setSetup(false)} busy={busy} />}
    {tab === "Medical History" && <MedicalHistory profile={profile} mutate={mutate} busy={busy} />}
    {tab === "Timeline" && <Timeline profile={profile} />}
    {tab === "Overview" && !setup && !plan && <div className="tracker-empty hero-empty"><HeartPulse size={32} /><h2>No health tracking started yet.</h2><p>Create a plan and record a baseline to begin tracking progress.</p><button className="button primary" onClick={() => setSetup(true)}>Start Health Tracking</button></div>}
    {tab === "Overview" && plan && !setup && <>
      <div className="plan-switcher"><div><b>Active tracking</b>{active.length ? active.map(item => <button className={idOf(item) === idOf(plan) ? "active" : ""} key={idOf(item)} onClick={() => setSelectedId(idOf(item))}>{item.title}</button>) : <small>No active plans</small>}</div>{past.length > 0 && <div><b>Past Health & Recovery</b>{past.map(item => <button className={idOf(item) === idOf(plan) ? "active" : ""} key={idOf(item)} onClick={() => setSelectedId(idOf(item))}><Archive size={13} /> {item.title}</button>)}</div>}</div>
      <div className="overview-grid"><article className="overview-card opi-overview-card"><span>Overall Progress Index <Info size={14}><title>OPI summarizes the health information you record in Sanjeevani for personal progress tracking. It is not a medical diagnosis.</title></Info></span><div className={`opi-ring ${latestOpi === null ? "empty-ring" : ""}`} style={{ "--opi": latestOpi ?? 0 }} role="img" aria-label={latestOpi === null ? "Overall Progress Index not yet available" : `Overall Progress Index ${latestOpi} out of 100`}><div><b>{latestOpi === null ? "—" : latestOpi}</b><small>/ 100</small></div></div><small>{latest ? `Recorded ${dateLabel(latest.date)}` : "Complete your first check-in"}</small></article><article className="overview-card"><span>Current Trend</span><b>{trendFor(plan)}</b><small>Recorded values only</small></article><article className="overview-card"><span>Tracking Duration</span><b>{duration} Days</b><small>Since {dateLabel(plan.startDate)}</small></article><article className="overview-card"><span>Latest Check-in</span><b>{latest ? dateLabel(latest.date) : "None"}</b><small>{plan.checkIns.length} total check-in{plan.checkIns.length === 1 ? "" : "s"}</small></article><article className="overview-card"><span>Active Tracking Plans</span><b>{active.length}</b><small>{plan.type}</small></article></div>
      <div className="tracker-columns">{plan.status === "active" ? <CheckInForm plan={plan} busy={busy} onSave={data => mutate("addCheckIn", [idOf(plan), data])} /> : <section className="tracker-panel"><span className="section-kicker">ARCHIVED RECOVERY</span><h2>Tracking completed</h2><div className="tracker-empty">This plan is preserved as a past health and recovery record. Reopen it to add new check-ins.</div></section>}<section className="tracker-panel"><div className="tracker-panel-head"><div><span className="section-kicker">RECOVERY PROGRESS</span><h2>Overall Progress Index</h2></div><div className="filter-row">{Object.keys(ranges).map(value => <button className={range === value ? "active" : ""} key={value} onClick={() => setRange(value)}>{value}</button>)}</div></div><LineChart points={points} label="Overall Progress" unit="%" /><p className="field-help"><Info size={13} /> OPI is a deterministic application-level progress indicator, not a medically validated score.</p></section></div>
      <div className="tracker-columns"><section className="tracker-panel"><div className="tracker-panel-head"><div><span className="section-kicker">INDIVIDUAL METRIC</span><h2>{selectedMetric?.label || "Metric progress"}</h2></div><select aria-label="Metric graph" value={selectedMetric?.key || ""} onChange={event => setMetricKey(event.target.value)}>{plan.metrics.map(metric => <option value={metric.key} key={metric.key}>{metric.label}</option>)}</select></div><LineChart points={metricPoints} valueKey="value" label={selectedMetric?.label} unit={selectedMetric?.unit} /></section><section className="tracker-panel"><span className="section-kicker">THEN VS NOW</span><h2>Starting point compared with current</h2><div className="comparison-list">{plan.metrics.map(metric => { const current = valuesOf(latest)[metric.key], baseline = metric.baseline, change = number(current) !== null && number(baseline) !== null && Number(baseline) !== 0 ? ((Number(current) - Number(baseline)) / Math.abs(Number(baseline))) * 100 : null; return <article key={metric.key}><div><small>{metric.label}</small><b>{String(baseline)}{metric.unit} → {current ?? "—"}{current !== undefined ? metric.unit : ""}</b></div><span>{change === null ? "No comparison yet" : `${Math.abs(change).toFixed(1)}% ${change < 0 ? "decrease" : "increase"}`}</span></article>; })}</div></section></div>
      <div className="tracker-columns"><section className="tracker-panel"><span className="section-kicker">THIS WEEK</span><h2>Weekly summary</h2>{(() => { const week = [...plan.checkIns].filter(item => (Date.now() - new Date(item.date)) / 864e5 <= 7).sort((a, b) => new Date(a.date) - new Date(b.date)); if (!week.length) return <div className="tracker-empty">No check-ins recorded in the last 7 days.</div>; const sentences = plan.metrics.flatMap(metric => { const recorded = week.map(item => number(valuesOf(item)[metric.key])).filter(value => value !== null); if (recorded.length < 2) return []; const direction = recorded.at(-1) > recorded[0] ? "increased" : recorded.at(-1) < recorded[0] ? "decreased" : "remained stable"; return [`${metric.label} ${direction} (${recorded[0]} to ${recorded.at(-1)}${metric.unit}).`]; }); return <><b>{week.length} check-in{week.length === 1 ? "" : "s"}</b><p>{sentences.length ? `During the last 7 days, ${sentences.join(" ")}` : "Add another check-in this week to compare recorded values."}</p></>; })()}</section><Milestones plan={plan} mutate={mutate} busy={busy} /></div>
      <DoctorSummary plan={plan} profile={profile} />
      <section className="tracker-panel record-management"><div><span className="section-kicker">TRACKING PLAN</span><h2>{plan.title}</h2><p>{plan.goal}</p></div><div>{plan.status === "active" ? <button className="button secondary" onClick={() => window.confirm("Complete and archive this tracking plan? Its full history will remain accessible.") && mutate("updatePlan", [idOf(plan), { status: "completed" }])}><Archive size={15} /> Complete Tracking</button> : <button className="button secondary" onClick={() => mutate("updatePlan", [idOf(plan), { status: "active" }])}><Activity size={15} /> Reopen Tracking</button>}<button className="button danger-button" onClick={() => window.confirm("Permanently delete this plan and all of its check-ins and milestones?") && mutate("deletePlan", [idOf(plan)])}><Trash2 size={15} /> Delete Plan</button>{onNavigate && <button className="button secondary" onClick={() => onNavigate("SOS Response")}>Emergency SOS</button>}</div></section>
      {plan.checkIns.length > 0 && <section className="tracker-panel"><span className="section-kicker">RECORDED CHECK-INS</span><h2>Check-in history</h2><div className="checkin-history">{[...plan.checkIns].sort((a, b) => new Date(b.date) - new Date(a.date)).map(item => <article key={idOf(item)}><div><b>{dateLabel(item.date)}</b><small>OPI: {number(item.opi) === null ? "Not calculated" : item.opi}</small>{item.notes && <p>{item.notes}</p>}</div><button className="icon-button danger" aria-label={`Delete check-in from ${dateLabel(item.date)}`} onClick={() => window.confirm("Delete this check-in?") && mutate("deleteCheckIn", [idOf(plan), idOf(item)])}><Trash2 size={15} /></button></article>)}</div></section>}
    </>}
  </section>;
}
